version: "3.7"
services:
  backend:
    build: ./backend
    command: ["sh", "/app/backend/scripts/run-prod.sh"]
    volumes:
      - backend_data:/root/uploads
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      DATABASE_URL: "mysql+pymysql://audino:audino@mysql/audino?charset=utf8mb4"
      JWT_SECRET_KEY: "secretkey"
      JWT_REDIS_STORE_URL: "redis://redis:6379/0"
    depends_on:
      - mysql
      - redis
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./frontend
    ports:
      - 8085:80
    depends_on:
      - backend
    networks:
      - frontend-network

  mysql:
    build: ./mysql
    volumes:
      - mysql_prod_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "audino"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "audino"
      MYSQL_PASSWORD: "audino"
    networks:
      - backend-network

  redis:
    build: ./redis
    networks:
      - backend-network

volumes:
  mysql_prod_data:
  backend_data:

networks:
  backend-network:
  frontend-network:
